
export const ROUTE_COMPONENTS = {
  ROOT: 'directorio',
  PAGE: 'pagina',
  CONTACT: {
    ROOT: 'contacto',
    NEW: 'nuevo',
    EDIT: 'editar'
  }
};

export const ROUTES = {
  DIRECTORY: ROUTE_COMPONENTS.ROOT,
  PAGE: num => ROUTE_COMPONENTS.ROOT + '/' + ROUTE_COMPONENTS.PAGE  + '/' + num,
  CONTACT: id => ROUTE_COMPONENTS.ROOT + '/' + ROUTE_COMPONENTS.CONTACT.ROOT + '/' + id,
  CONTACT_NEW: ROUTE_COMPONENTS.ROOT + '/' + ROUTE_COMPONENTS.CONTACT.ROOT + '/' + ROUTE_COMPONENTS.CONTACT.NEW,
  CONTACT_EDIT: id => ROUTE_COMPONENTS.ROOT + '/' + ROUTE_COMPONENTS.CONTACT.ROOT + '/' + id + '/' + ROUTE_COMPONENTS.CONTACT.EDIT
};
